POST http://localhost:8080/user/register
Content-Type: application/json

{
  "firstName": "tom",
  "lastName": "tommy",
  "userName": "tom768",
  "email": "tom@email.com"
}

### password:- E6EwClsWOd
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "userName": "tom768",
  "password": "E6EwClsWOd"
}